### ISSUE TITLE
Using the current console window on Windows 7

### ISSUE THREAD

**Issue by Mattiwatti** [bb107/WinSudo#1]
Hi,

You can do the following to create a process that inherits the current console window on Windows 7. The important parts are (1) changing the token session ID to that of the current process, and (2) using `CreateProcessInternalW` instead of `CreateProcessWithTokenW`.

1. Acquire `SE_DEBUG_PRIVILEGE`.
2. Acquire `SE_IMPERSONATE_PRIVILEGE`.
3. Open a system process (either `winlogon.exe` or `lsass.exe` works, I used winlogon).
4. Open the system process token with `TOKEN_DUPLICATE` access.
5. Duplicate the token with `TOKEN_IMPERSONATE` access.
6. Impersonate the system process.
7. Acquire `SE_ASSIGNPRIMARYTOKEN_PRIVILEGE` for the impersonating thread only. This is needed to create a process with a primary token.
8. Acquire `SE_TCB_PRIVILEGE` for the impersonating thread only. This is needed to change the session ID of the lsass token.
9. Use `SetTokenInformation`/`NtSetInformationToken` with class `TokenSessionId` to change the lsass.exe token session ID to the current process session ID (can be queried from the PEB or using `ProcessIdToSessionId`).
10. Call `CreateProcessInternalW` with the lsass.exe token handle as the first parameter. `CreateProcessInternalW` is a kernel32 export but it is not in kernel32.lib, so you can either `GetProcAddress` it or use a custom .lib file that does have the export.
11. Drop impersonation.

Note that I'm probably doing a bunch of stuff (e.g. acquiring privileges) that is not needed or can be done more easily if you simply use the existing `lsass.exe` token for impersonation. I only added this stuff to `main.cpp` prior to process creation and it works. (The code is a mess though, hence no PR.)

CreateProcessInternalW signature:
```C++
extern "C"
WINBASEAPI
BOOL
WINAPI
CreateProcessInternalW(
    _In_opt_ HANDLE hUserToken,
    _In_opt_ LPCWSTR lpApplicationName,
    _Inout_opt_ LPWSTR lpCommandLine,
    _In_opt_ LPSECURITY_ATTRIBUTES lpProcessAttributes,
    _In_opt_ LPSECURITY_ATTRIBUTES lpThreadAttributes,
    _In_ BOOL bInheritHandles,
    _In_ DWORD dwCreationFlags,
    _In_opt_ LPVOID lpEnvironment,
    _In_opt_ LPCWSTR lpCurrentDirectory,
    _In_ LPSTARTUPINFOW lpStartupInfo,
    _Out_ LPPROCESS_INFORMATION lpProcessInformation,
    _Outptr_opt_ PHANDLE hRestrictedUserToken
    );
```

**Comment by bb107** [comment]
When I test with Windows 10, `CreateProcessInternalW` behaves the same as `CreateProcessAsUser`. When it has the SE_ASSIGNPRIMARYTOKEN_PRIVILEGE privilege, it returns a failure with error code ERROR_ACCESS_DENIED. Can it work in Windows 7?
![TIM截图20190412004733](https://user-images.githubusercontent.com/20726245/55975998-c24e5a80-5cbd-11e9-9369-147e054a59a0.png)

**Comment by Mattiwatti** [comment]
For me it works on Windows 7 and 10. This is the thread token:

![token](https://i.imgur.com/vzLITfP.png)
The token has session ID 1 because it's from winlogon, but I get the same result with a token from lsass.
This is how I'm obtaining the token:

```C++
NTSTATUS
ImpersonateWinlogon(
    )
{
    // Open winlogon.exe with the access rights needed for NtOpenProcessToken
    HANDLE ProcessHandle;
    NTSTATUS Status = OpenSessionProcess(&ProcessHandle,
                                        static_cast<PCWSTR>(L"winlogon.exe"),
                                        NtCurrentPeb()->SessionId,
                                        PROCESS_QUERY_LIMITED_INFORMATION | PROCESS_DUP_HANDLE);
    if (!NT_SUCCESS(Status))
        return Status;

    // Open winlogon.exe process token
    HANDLE TokenHandle;
    Status = NtOpenProcessTokenEx(ProcessHandle,
                                TOKEN_DUPLICATE,
                                0,
                                &TokenHandle);
    if (!NT_SUCCESS(Status))
    {
        NtClose(ProcessHandle);
        return Status;
    }

    // Duplicate token handle for impersonation
    OBJECT_ATTRIBUTES ObjectAttributes;
    InitializeObjectAttributes(&ObjectAttributes, nullptr, 0, nullptr, nullptr);
    SECURITY_QUALITY_OF_SERVICE QoS;
    QoS.Length = sizeof(SECURITY_QUALITY_OF_SERVICE);
    QoS.ImpersonationLevel = SecurityImpersonation;
    QoS.ContextTrackingMode = SECURITY_DYNAMIC_TRACKING;
    QoS.EffectiveOnly = FALSE;
    ObjectAttributes.SecurityQualityOfService = &QoS;

    HANDLE NewTokenHandle;
    Status = NtDuplicateToken(TokenHandle,
                            TOKEN_IMPERSONATE,
                            &ObjectAttributes,
                            FALSE,
                            TokenImpersonation,
                            &NewTokenHandle);
    if (!NT_SUCCESS(Status))
    {
        NtClose(TokenHandle);
        NtClose(ProcessHandle);
        return Status;
    }

    // Impersonate winlogon.exe
    Status = NtSetInformationThread(NtCurrentThread,
                                    ThreadImpersonationToken,
                                    &NewTokenHandle,
                                    sizeof(NewTokenHandle));

    NtClose(ProcessHandle);
    NtClose(TokenHandle);
    NtClose(NewTokenHandle);

    return Status;
}
```

**Comment by bb107** [comment]
Great, I set up the token session ID and it runs successfully! Thank you.
